# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographical',
            name='food',
        ),
        migrations.RemoveField(
            model_name='season',
            name='food',
        ),
    ]
