# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients_info', '0002_auto_20171108_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='type',
            field=models.CharField(default=b'type here', max_length=50),
        ),
    ]
