# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 09:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients_info', '0003_auto_20171108_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodFoundInSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrients_info.Food')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrients_info.Season')),
            ],
        ),
    ]
