# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients_info', '0004_foodfoundinseason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='lack',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='surplus',
        ),
        migrations.AddField(
            model_name='disease',
            name='type',
            field=models.CharField(choices=[(b'lack', b'lack'), (b'surplus', b'surplus')], default=b'lack', max_length=10),
        ),
    ]
