# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients_info', '0005_auto_20171108_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='type',
            field=models.CharField(choices=[('lack', 'lack'), ('surplus', 'surplus')], default='lack', max_length=10),
        ),
        migrations.AlterField(
            model_name='people',
            name='type',
            field=models.CharField(default='type here', max_length=50),
        ),
    ]
